language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_install:
 - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2739/forge-1.12.2-14.23.4.2739-mdk.zip
 - unzip -n forge-1.12.2-14.23.4.2739-mdk.zip
 - rm forge-1.12.2-14.23.4.2739-mdk.zip
install: ./gradlew setupCiWorkspace
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8