language: java
install:
  - ./gradlew setupCIWorkspace
  -  sed -i 's:^[ \t]*build_number[ \t]*=\([ \t]*.*\)$:build_number=\' gradle.properties
script:
  - ./gradlew build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle
    - .gradle
    - gradle
jdk:
  - oraclejdk8